sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cyVH3fhcVkHCN8ZEOkDG5NEZKbcig4MZhQdpigSTl6824RIFeYoSercIX0P4V3f5KAdFgsJMmoDKRC3Yd53v1EomEHgRqjWQkOqyD6YZ1WHuoMjmi9fr5IzSvNuVsAz/j3b2dj0QyX1BP8OVtSuA7tzr2WUXY8a9iA2OCmOzv+L4pC3bmaWYCEVnmLBlPkcquX/XWlrfpWx1HRd6rgE7dGe+0Pg5He+Zu+k8riVhfWl8mcRvt1xRxJvrhxbk8eNq+wgl5UEd2vImdiXh4dzVwW71bkCCMmnYeKm0lC262GDGmGyoeiJv8y+71j2INz0TgR+eSn8NTyX8C+T75Pd7s+1lQroKYygOO1MrVkCNBtBDJgzgxBCoaCjFNLnu4S0vEQwMXS3OMYUtUzLDk8KN1JLuQ25+gPai3605rjwUYehlt+GHLs+usR6VutCz39bQ8JMzn+5fk2AJ1yC/ff68qc7c6Iz2lrRNi7lDNSck2Ou4oOw5Y+3UcS2dtElRTekPz9tiQMejXqa5BrTDPt33dfaQECGaTqWhtxc7fxFvXxKA6n/X6ajjmZwrAUeDmnyCL3hWMR0Cb92xbVFMTWyq91Uxh+ctjnigUd/pFDUtIk1XRlnj66NT9NuBa1xjN0I7G00+4YKXmLdk3JU1NtEjFYamjbs21uG/l/NQI5Qm52g=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Narrative-of-Sojourner-Truth_1674
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy